# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd-ninja" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5762e2b0119aa2f8cda42f7663e01ae57d80c604298d64393b44edd672203ba7"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1f22ad96116e2e6777856b62297226b55e44471eefdd02e92b8e441796c969c"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f76b042f6a8511e58002382c11a543e2f8fa62a185633f577253c1c6ea9ef6b7"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d4b7e6bfac885274dd66c54b317455a835fdf92a0d9636c35e75d7164e043ec0"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cmd-ninja"
  desc "Plain English in, a safe shell command on your prompt line"
  homepage "https://github.com/llm-books/cmd-ninja"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ninja"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ninja"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This installs a `ninja` binary, which clashes with the Ninja build
    system if you have it installed.

    Add the shell hook to your rc file:
      eval "$(ninja init zsh)"     # or bash/fish
    and export an API key, e.g.:
      export ANTHROPIC_API_KEY=...   # or GEMINI/OPENAI/MISTRAL_API_KEY
  EOS
end
