# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd-ninja" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "3bcef20869566218268e9b9561083e1d867292497adf9069f7c3da216e35ae3d"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e2af4809cddf42e0e28d5b7f15a6edd404d62fdda09872305c6742322d92e41b"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "83f2b55d22a13da36702fbe046e8a6d6a8e4ed15cbc227383342d309102e49da"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "3fa4a078bdc1ae57020a7bf6cca8e27250cb90b1f9f8d863233b4cfd94793f9d"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cmd-ninja"
  desc "Type what you need your cmd to do, press Ctrl-G, get the full command. Safe commands land on your prompt, dangerous ones don't."
  homepage "https://github.com/llm-books/cmd-ninja"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ninja"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ninja"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This installs a `ninja` binary, which clashes with the Ninja build
    system if you have it installed.

    Add the shell hook to your rc file:
      eval "$(ninja init zsh)"     # or bash/fish
    and export an API key, e.g.:
      export ANTHROPIC_API_KEY=...   # or GEMINI/OPENAI/MISTRAL_API_KEY
  EOS
end
