# This file was generated by GoReleaser. DO NOT EDIT.
cask "cmd-ninja" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "8502a175196940106a0770fb368979584e218a80cf6aa93bb825ba2bf366cdfe"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c1382aa6d95bc2c8e15ed06c057b3a2d21945843109f8759b53b4e926050e8fa"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "1ddfa895e62ad2ce93bb15428ec80ecd2d887573f129a3fbbe79386607ea385f"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a61daec147ba25c6ae666f5c4222af1fca1a35723875fd4370acca416cb4765f"
      url "https://github.com/llm-books/cmd-ninja/releases/download/v#{version}/cmd-ninja_#{version}_linux_arm64.tar.gz"
    end
  end

  name "cmd-ninja"
  desc "Type what you need your cmd to do, press Ctrl-G, get the full command. Safe commands land on your prompt, dangerous ones don't."
  homepage "https://github.com/llm-books/cmd-ninja"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ninja"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ninja"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    This installs a `ninja` binary, which clashes with the Ninja build
    system if you have it installed.

    Add the shell hook to your rc file:
      eval "$(ninja init zsh)"     # or bash/fish
    and export an API key, e.g.:
      export ANTHROPIC_API_KEY=...   # or GEMINI/OPENAI/MISTRAL_API_KEY
  EOS
end
